FROM alpine

RUN apk add --no-cache bash \
                       clang-format \
                       git \
                       perl \
                       python \
                       yarn 
