.\" $Id$
.\"
.\" Copyright (c) 2008 Charles Kerr
.\"
.\" This file is licensed by the GPL version 2.  Works owned by the
.\" Transmission project are granted a special exemption to clause 2(b)
.\" so that the bulk of its code can remain under the MIT license. 
.\" This exemption does not extend to derived works not owned by
.\" the Transmission project.

.Dd May 19, 2008
.Dt TRANSMISSION-DAEMON 1
.Os
.Sh NAME
.Nm transmission-daemon
.Nd a bittorrent client
.Sh SYNOPSIS
.Bk -words
.Nm transmission-daemon
.Fl h
.Nm
.Op Fl f
.Op Fl a Ar (+|-)x.x.x.x[/x],...
.Op Fl g Ar directory
.Op Fl p Ar port
.Ek
.Sh DESCRIPTION
The
.Nm
program is a daemon-based Transmission session that can be controlled
via RPC commands by
.Xr transmission-remote 1
or
.Xr Clutch 1
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl a Fl -acl Ar (+|-)x.x.x.x[/x],...
Specify access control list (ACL) to control which hosts may submit RPC requests.
ACL is a comma separated list of IP subnets,
each subnet is prepended by '-' or '+' sign.
Plus means allow, minus means deny.
If subnet mask is omitted, like "-1.2.3.4", then it means that single IP address.
Masks may vary from 0 to 32 inclusive.
Default: +127.0.0.1
.It Fl f Fl -foreground
Run in the foreground and print errors to stderr instead of forking
and logging errors with syslog.
.It Fl g Fl -config-dir Ar directory
Where to look for .torrent files and daemon-config.benc on startup.
.It Fl h Fl -help
Print command-line option descriptions.
.It Fl p Fl -port Ar port
Port to open and listen for RPC requests on.  Default: 9091
.El

.Sh FILES
.Pa ~/.transmission
.Sh AUTHORS
.An -nosplit
The
.Nm
program was written by
.An Charles Kerr ,
.An Josh Elsasser ,
.An Eric Petit ,
and
.An Mitchell Livingston .
.Sh SEE ALSO
.Xr transmissioncli 1 ,
.Xr transmission 1 ,
.Xr transmission-remote 1
.Pp
http://www.transmissionbt.com/
