.Dd July 21, 2008
.Dt TRANSMISSION-DAEMON 1

.Sh NAME
.Nm transmission-daemon
.Nd a bittorrent client
.Sh SYNOPSIS
.Bk -words
.Nm transmission-daemon
.Fl h
.Nm
.Op Fl a Ar x.x.x.x,...
.Op Fl b | B
.Op Fl f
.Op Fl g Ar directory
.Op Fl h
.Op Fl p Ar port
.Op Fl t | T
.Op Fl u Ar username
.Op Fl v Ar password
.Op Fl w Ar download-dir
.Ek

.Sh DESCRIPTION
.Nm
is a daemon-based Transmission session that can be controlled
via RPC commands from transmission's web interface or
.Xr transmission-remote 1 .

.Sh OPTIONS
.Bl -tag -width Ds

.It Fl a Fl -allowed Ar x.x.x.x,...
Allow RPC access to a comma-delimited whitelist of IP addresses.
Wildcards can be specified in an address by using '*'.
Default: "127.0.0.1"
Example: "127.0.0.*,192.168.1.*"

.It Fl b Fl -blocklist
Enable peer blocklists.  Transmission understands the bluetack blocklist file format.
New blocklists can be added by copying them into the config-dir's "blocklists" subdirectory.

.It Fl B Fl -no-blocklist
Disble blocklists.

.It Fl f Fl -foreground
Run in the foreground and print errors to stderr.

.It Fl g Fl -config-dir Ar directory
Where to look for .torrent and config files on startup.

.It Fl h Fl -help
Print command-line option descriptions.

.It Fl p Fl -port Ar port
Port to open and listen for RPC requests on.  Default: 9091

.It Fl t Fl -auth
Require clients to authenticate themselves.
This doesn't do much good unless
.Ar username
and
.Ar password
are also set.

.It Fl T Fl -no-auth
Don't require authentication from clients.

.It Fl u Fl -username Ar username
Used for client authentication.

.It Fl v Fl -password Ar password
Used for client authentication.

.It Fl w Fl -download-dir
Where to store downloaded data.

.El

.Sh ENVIRONMENT
.Bl -tag -width Fl
.It Ev TRANSMISSION_HOME
Sets the default config-dir.
.El


.Sh FILES
.Bl -tag -width Ds -compact
.It ~/.config/transmission-daemon
The config-dir used when neither
.Op Ev TRANSMISSION_HOME
nor
.Op Fl g
is specified.
.El


.Sh AUTHORS
.An -nosplit
.An Charles Kerr ,
.An Josh Elsasser ,
.An Eric Petit ,
and
.An Mitchell Livingston .

.Sh SEE ALSO
.Xr transmissioncli 1 ,
.Xr transmission 1 ,
.Xr transmission-remote 1
.Pp
http://www.transmissionbt.com/
