.Dd July 21, 2008
.Dt TRANSMISSION-DAEMON 1
.Sh NAME
.Nm transmission-daemon
.Nd a bittorrent client
.Sh SYNOPSIS
.Bk -words
.Nm transmission-daemon
.Fl h
.Nm
.Op Fl a Ar x.x.x.x,...
.Op Fl b | B
.Op Fl c Ar directory
.Op Fl C
.Op Fl d
.Op Fl f
.Op Fl g Ar directory
.Op Fl h
.Op Fl p Ar port
.Op Fl t | T
.Op Fl u Ar username
.Op Fl v Ar password
.Op Fl P Ar port
.Op Fl m | M
.Op Fl l Ar limit
.Op Fl L Ar limit
.Op Fl er | ep | et
.Op Fl utp | no-utp
.Op Fl V
.Op Fl w Ar download-dir
.Op Fl e Ar logfile
.Op Fl log-error | log-info | log-debug
.Ek
.Sh DESCRIPTION
.Nm
is a daemon-based Transmission session that can be controlled
via RPC commands from transmission's web interface or
.Xr transmission-remote 1 .
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl a Fl -allowed Ar x.x.x.x,...
Allow RPC access to a comma-delimited whitelist of IP addresses.
Wildcards can be specified in an address by using '*'.
Default: "127.0.0.1"
Example: "127.0.0.*,192.168.1.*"
.It Fl b Fl -blocklist
Enable peer blocklists. Transmission understands the bluetack blocklist file format.
New blocklists can be added by copying them into the config-dir's "blocklists" subdirectory.
.It Fl c Ar directory
Directory to watch for new .torrent files to be added. As they are added to this directory,
the daemon will load them into Transmission.
.It Fl C
Do not watch for new .torrent files.
.It Fl B Fl -no-blocklist
Disble blocklists.
.It Fl d
Dump transmission-daemon's settings to stderr.
.It Fl f Fl -foreground
Run in the foreground and print errors to stderr.
.It Fl g Fl -config-dir Ar directory
Where to look for configuration files. This can be used to swap between using the cli, daemon, gtk, and qt clients.
See https://github.com/transmission/transmission/wiki/Configuration-Files for more information.
.It Fl er Fl -encryption-required
Encrypt all peer connections.
.It Fl ep Fl -encryption-preferred
Prefer encrypted peer connections.
.It Fl et Fl -encryption-tolerated
Prefer unencrypted peer connections.
.It Fl gsr Fl -global-seedratio Ar ratio
All torrents, unless overridden by a per-torrent setting, should seed until a specific
.Ar ratio
.It Fl GSR Fl -no-global-seedratio
All torrents, unless overridden by a per-torrent setting, should seed regardless of ratio
.It Fl h Fl -help
Print command-line option descriptions.
.It Fl -incomplete-dir Ar dir
When adding new torrents, store their contents in
.Ar directory
until the torrent is done.
.It Fl -no-incomplete-dir
Don't store incomplete torrents in a different directory.
.It Fl i Fl -bind-address-ipv4
Listen for IPv4 BitTorrent connections on a specific address. Only one IPv4 listening address is allowed. Default: 0.0.0.0 (All addresses)
.It Fl I Fl -bind-address-ipv6
Listen for IPv6 BitTorrent connections on a specific address. Only one IPv6 listening address is allowed. Default: :: (All addresses)
.It Fl r Fl -rpc-bind-address
Listen for RPC connections on a specific address. This must be an IPv4 address. Only one RPC listening address is allowed. Default: 0.0.0.0 (All addresses)
.It Fl -paused
Pause all torrents on startup
.It Fl L Fl -peerlimit-global Ar limit
Overall peer limit. Useful on embedded systems where the default might be unsuitable. Default: 240
.It Fl l Fl -peerlimit-torrent Ar limit
Peer limit per torrent. Useful on embedded systems where the default might be unsuitable. Default: 60
.It Fl m Fl -portmap
Enable portmapping via NAT-PMP or UPnP
.It Fl M Fl -no-portmap
Disable portmapping
.It Fl o Fl -dht
Enable distributed hash table (DHT).
.It Fl O Fl -no-dht
Disable distribued hash table (DHT).
.It Fl p Fl -port Ar port
Port to open and listen for RPC requests on. Default: 9091
.It Fl P, -peerport Ar port
Port to listen for incoming peers on. Default: 51413
.It Fl t Fl -auth
Require clients to authenticate themselves.
This doesn't do much good unless
.Ar username
and
.Ar password
are also set.
.It Fl T Fl -no-auth
Don't require authentication from clients.
.It Fl u Fl -username Ar username
Used for client authentication.
.It Fl v Fl -password Ar password
Used for client authentication.
.It Fl V Fl -version
Show version number and exit
.It Fl -utp
Enable uTP for peer connections.
.It Fl -no-utp
Disable uTP for peer connections.
.It Fl w Fl -download-dir
Where to store downloaded data.
.It Fl e Fl -logfile
Where to store transmission's log messages.
.It Fl -log-error
Show error messages
.It Fl -log-info
Show error and info messages
.It Fl -log-debug
Show error, info, and debug messages
.El
.Sh ENVIRONMENT
.Bl -tag -width Fl
.It Ev http_proxy
libcurl uses this environment variable when performing tracker announces.
.It Ev TRANSMISSION_HOME
Sets the default config-dir.
.El
.Sh FILES
.Bl -tag -width Ds -compact
.It ~/.config/transmission-daemon
The config-dir used when neither
.Op Ev TRANSMISSION_HOME
nor
.Op Fl g
is specified.
See https://github.com/transmission/transmission/wiki/Configuration-Files for more information.
.El
.Sh AUTHORS
.An -nosplit
.An Jordan Lee ,
.An Josh Elsasser ,
.An Eric Petit ,
and
.An Mitchell Livingston .
.Sh SEE ALSO
.Xr transmission-create 1 ,
.Xr transmission-daemon 1 ,
.Xr transmission-edit 1 ,
.Xr transmission-gtk 1 ,
.Xr transmission-qt 1 ,
.Xr transmission-remote 1 ,
.Xr transmission-show 1
.Pp
https://transmissionbt.com/
