.Dd May 20, 2008
.Dt TRANSMISSION-REMOTE 1
.Os
.Sh NAME
.Nm transmission-remote
.Nd a remote control utility for
.Xr transmission-daemon 1
and
.Xr transmission 1
.Sh SYNOPSIS
.Bk -words
.Nm
.Op Ar host:port | host | port
.Op Fl a Ar torrent-files
.Op Fl d Ar number
.Op Fl D
.Op Fl e Ar mode
.Op Fl f
.Op Fl g
.Op Fl h
.Op Fl i
.Op Fl l
.Op Fl m
.Op Fl M
.Op Fl n Ar user:pass
.Op Fl p Ar port
.Op Fl r
.Op Fl s
.Op Fl S
.Op Fl t Ar all | Ar id | Ar hash
.Op Fl u Ar number
.Op Fl U
.Op Fl v
.Op Fl w Ar download-dir
.Op Fl x
.Op Fl X
.Ek
.Sh DESCRIPTION
.Nm
is a remote control utility for
.Xr transmission 1 
and
.Xr transmission-daemon 1 .
.Pp
By default,
.Nm
connects to the transmission session at localhost:9091.
Other sessions can be controlled by specifying a different host and/or port.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl a Fl -add Ar torrent-file
Add metainfo
.Ar torrent-file(s) .

.It Fl d Fl -downlimit Ar limit
Limit the download speed to
.Ar limit
kilobytes per second.

.It Fl D Fl -no-downlimit
Remove the download limit.

.It Fl e Fl -encryption Ar required
Require all peer connections to be encrypted.
.It Fl e Fl -encryption Ar preferred
Prefer encrypted peer connections.
.It Fl e Fl -encryption Ar tolerated
Prefer unencrypted peer connections.

.It Fl f Fl -files
Get a file list for the current torrent(s)

.It Fl h Fl -help
Print command-line option descriptions.

.It Fl i Fl -info Ar id | torrent-hash
Show details of the current torrent(s)

.It Fl l Fl -list
List all torrents

.It Fl m Fl -portmap
Enable portmapping via NAT-PMP or UPnP
.It Fl M Fl -no-portmap
Disable portmapping

.It Fl n Fl -auth Ar user:pass
.Ar Username
and
.Ar password
for authentication

.It Fl p Fl -port Ar port
Set the
.Ar port
for use when listening for incoming peer connections

.It Fl r Fl -remove
Remove the current torrent(s).  This does not delete the downloaded data.

.It Fl s Fl -start
Start the current torrent(s)

.It Fl S Fl -stop
Stop the current torrent(s) from downloading or seeding

.It Fl t Fl -torrent Ar all | id | torrent-hash
Set the current torrent(s) for use by subsequent options.
.Ar all
will apply following requests to all torrents, while specific torrents can be chosen by
.Ar id
or
.Ar hash .

.It Fl u Fl -uplimit Ar limit
Limit the upload speed to
.Ar limit
kilobytes per second.
.It Fl U Fl -no-uplimit
Remove the upload limit.

.It Fl v Fl -verify
Verify the current torrent(s)

.It Fl w Fl -download-dir Ar directory
Use
.Ar directory
as the default location for newly added torrents to download files to.

.It Fl x
Enable peer exchange (PEX).
.It Fl X
Disable peer exchange (PEX).

.El
.Sh EXAMPLES
Show all torrents, their ID numbers, and their status:
.Pp
.Dl transmission-remote -l
.Pp
Pause torrent #12:
.Pp
.Dl transmission-remote -t 12 -S
.Dl transmission-remote --torrent=12 --stop
.Pp
Start all torrents:
.Pp
.Dl transmission-remote -t all -s
.Dl transmission-remote --torrent=all --start
.Pp
Set download and upload limits to 100 KiB/sec and 20 KiB/sec:
.Pp
.Dl transmission-remote -d 100 -u 20
.Dl transmission-remote -d=100 -u=20
.Pp
Add two torrents:
.Pp
.Dl transmission-remote -a one.torrent two.torrent

.Sh AUTHORS
.An -nosplit
.An Charles Kerr ,
.An Josh Elsasser ,
.An Eric Petit ,
and
.An Mitchell Livingston .

.Sh SEE ALSO
.Xr transmissioncli 1 ,
.Xr transmission-daemon 1 ,
.Xr transmission 1

.Pp
http://www.transmissionbt.com/
