.\" Copyright (c) 2007 Joshua Elsasser
.\"
.\" Permission is hereby granted, free of charge, to any person obtaining a
.\" copy of this software and associated documentation files (the "Software"),
.\" to deal in the Software without restriction, including without limitation
.\" the rights to use, copy, modify, merge, publish, distribute, sublicense,
.\" and/or sell copies of the Software, and to permit persons to whom the
.\" Software is furnished to do so, subject to the following conditions:
.\"
.\" The above copyright notice and this permission notice shall be included in
.\" all copies or substantial portions of the Software.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
.\" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
.\" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
.\" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
.\" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
.\" FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
.\" DEALINGS IN THE SOFTWARE.
.Dd May 20, 2008
.Dt TRANSMISSION-GTK 1
.Os
.Sh NAME
.Nm transmission-gtk
.Nd a bittorrent client
.Sh SYNOPSIS
.Nm transmission-gtk
.Fl ?
.Nm
.Op Fl pqm
.Op Ar torrent-file ...
.Sh DESCRIPTION
.Nm
is a fast and easy BitTorrent client.
.Pp
BitTorrent is a peer-to-peer file transfer protocol which uses a
metainfo file (usually with the .torrent file extension) and a central
tracker to distribute file data amongst a group of peers. For more
information on the BitTorrent protocol see http://www.bittorrent.org/
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl ? Fl -help
Show help options
.It Fl p Fl -paused
Start with all torrents paused
.It Fl m Fl -minimized
Start minimized in notification area
.It Fl g, Fl -config-dir Ar directory
Where to look for configuration files. This can be used to swap between using the cli, daemon, gtk, and qt clients.
See https://github.com/transmission/transmission/wiki/Configuration-Files for more information.
.El
.Pp
Multiple .torrent files may be added at startup
by appending them on the command line.
If
.Nm
is already running, the torrents will be added to the running instance.
.Sh ENVIRONMENT
.Bl -tag -width Fl
.It Ev TRANSMISSION_HOME
Sets the default config-dir.
.It Ev http_proxy
libcurl uses this environment variable when performing tracker announces. If set, this overrides the GNOME proxy preferences.
.El
.Sh FILES
.Bl -tag -width Ds -compact
.It ~/.config/transmission
The config-dir used when neither
.Op Ev TRANSMISSION_HOME
nor
.Op Fl g
is specified.
.El
.Sh AUTHORS
.An -nosplit
.Nm
was written by
.An Charles Kerr ,
.An Josh Elsasser ,
.An Eric Petit ,
.An Mitchell Livingston ,
and
.An Mike Gelfand .
.Sh SEE ALSO
.Xr transmission-create 1 ,
.Xr transmission-daemon 1 ,
.Xr transmission-edit 1 ,
.Xr transmission-gtk 1 ,
.Xr transmission-qt 1 ,
.Xr transmission-remote 1 ,
.Xr transmission-show 1
.Pp
https://transmissionbt.com/
