const char * fallback_ui_file =
"<ui>\n"
"  <menubar name='main-window-menu'>\n"
"    <menu action='torrent-menu'>\n"
"      <menuitem action='add-torrent'/>\n"
"      <menuitem action='create-torrent'/>\n"
"      <separator/>\n"
"      <menuitem action='start-torrent'/>\n"
"      <menuitem action='update-tracker'/>\n"
"      <menuitem action='pause-torrent'/>\n"
"      <menuitem action='verify-torrent'/>\n"
"      <menuitem action='remove-torrent'/>\n"
"      <menuitem action='show-torrent-details'/>\n"
"      <separator/>\n"
"      <menuitem action='close'/>\n"
"      <menuitem action='quit'/>\n"
"    </menu>\n"
"    <menu action='edit-menu'>\n"
"      <menuitem action='select-all'/>\n"
"      <menuitem action='unselect-all'/>\n"
"      <separator/>\n"
"      <menuitem action='edit-preferences'/>\n"
"    </menu>\n"
"    <menu action='view-menu'>\n"
"      <menuitem action='minimal-view'/>\n"
"      <menuitem action='show-toolbar'/>\n"
"      <menuitem action='show-filter-bar'/>\n"
"      <menuitem action='show-status-bar'/>\n"
"      <separator/>\n"
"      <menuitem action='sort-by-activity'/>\n"
"      <menuitem action='sort-by-name'/>\n"
"      <menuitem action='sort-by-progress'/>\n"
"      <menuitem action='sort-by-state'/>\n"
"      <menuitem action='sort-by-tracker'/>\n"
"      <menuitem action='sort-reversed'/>\n"
"    </menu>\n"
"    <menu action='help-menu'>\n"
"      <menuitem action='toggle-message-log'/>\n"
"      <menuitem action='show-stats'/>\n"
"      <separator/>\n"
"      <menuitem action='show-about-dialog'/>\n"
"    </menu>\n"
"  </menubar>\n"
"\n"
"  <toolbar name='main-window-toolbar'>\n"
"    <toolitem action='add-torrent'/>\n"
"    <toolitem action='start-torrent'/>\n"
"    <toolitem action='pause-torrent'/>\n"
"    <toolitem action='remove-torrent'/>\n"
"    <separator/>\n"
"    <toolitem action='show-torrent-details'/>\n"
"  </toolbar>\n"
"\n"
"  <popup name='main-window-popup'>\n"
"    <menuitem action='show-torrent-details'/>\n"
"    <separator/>\n"
"    <menuitem action='start-torrent'/>\n"
"    <menuitem action='pause-torrent'/>\n"
"    <menuitem action='verify-torrent'/>\n"
"    <menuitem action='update-tracker'/>\n"
"    <separator/>\n"
"    <menuitem action='remove-torrent'/>\n"
"  </popup>\n"
"\n"
"  <popup name='icon-popup'>\n"
"    <menuitem action='add-torrent'/>\n"
"    <separator/>\n"
"    <menuitem action='toggle-main-window'/>\n"
"    <menuitem action='toggle-message-log'/>\n"
"    <menuitem action='show-about-dialog'/>\n"
"    <separator/>\n"
"    <menuitem action='quit'/>\n"
"  </popup>\n"
"\n"
"  <popup name='file-popup'>\n"
"    <menu action='priority-menu'>\n"
"      <menuitem action='priority-high'/>\n"
"      <menuitem action='priority-normal'/>\n"
"      <menuitem action='priority-low'/>\n"
"    </menu>\n"
"  </popup>\n"
"\n"
"</ui>";

