# CMake generated Testfile for 
# Source directory: X:/transmission-jr/tests/utils
# Build directory: X:/transmission-jr/build-dbg/tests/utils
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(transmission-show-bittorrent-v2-hybrid-test "X:/cmake/bin/cmake.exe" "-D" "transmission_show:string=X:/transmission-jr/build-dbg/utils/transmission-show.exe" "-D" "torrent_file:string=assets/bittorrent-v2-hybrid-test.torrent" "-D" "reference_file:string=X:/transmission-jr/tests/utils/assets/bittorrent-v2-hybrid-test.show" "-P" "X:/transmission-jr/tests/utils/run_transmission_show.cmake")
set_tests_properties(transmission-show-bittorrent-v2-hybrid-test PROPERTIES  WORKING_DIRECTORY "X:/transmission-jr/tests/utils" _BACKTRACE_TRIPLES "X:/transmission-jr/tests/utils/CMakeLists.txt;2;add_test;X:/transmission-jr/tests/utils/CMakeLists.txt;14;AddShowTest;X:/transmission-jr/tests/utils/CMakeLists.txt;0;")
add_test(transmission-show-inner-sanctum "X:/cmake/bin/cmake.exe" "-D" "transmission_show:string=X:/transmission-jr/build-dbg/utils/transmission-show.exe" "-D" "torrent_file:string=assets/Inner_Sanctum_movie_archive.torrent" "-D" "reference_file:string=X:/transmission-jr/tests/utils/assets/Inner_Sanctum_movie_archive.show" "-P" "X:/transmission-jr/tests/utils/run_transmission_show.cmake")
set_tests_properties(transmission-show-inner-sanctum PROPERTIES  WORKING_DIRECTORY "X:/transmission-jr/tests/utils" _BACKTRACE_TRIPLES "X:/transmission-jr/tests/utils/CMakeLists.txt;2;add_test;X:/transmission-jr/tests/utils/CMakeLists.txt;15;AddShowTest;X:/transmission-jr/tests/utils/CMakeLists.txt;0;")
add_test(transmission-show-thor "X:/cmake/bin/cmake.exe" "-D" "transmission_show:string=X:/transmission-jr/build-dbg/utils/transmission-show.exe" "-D" "torrent_file:string=assets/Thor_and_the_Amazon_Women.avi.torrent" "-D" "reference_file:string=X:/transmission-jr/tests/utils/assets/Thor_and_the_Amazon_Women.avi.show" "-P" "X:/transmission-jr/tests/utils/run_transmission_show.cmake")
set_tests_properties(transmission-show-thor PROPERTIES  WORKING_DIRECTORY "X:/transmission-jr/tests/utils" _BACKTRACE_TRIPLES "X:/transmission-jr/tests/utils/CMakeLists.txt;2;add_test;X:/transmission-jr/tests/utils/CMakeLists.txt;16;AddShowTest;X:/transmission-jr/tests/utils/CMakeLists.txt;0;")
add_test(transmission-show-ubuntu "X:/cmake/bin/cmake.exe" "-D" "transmission_show:string=X:/transmission-jr/build-dbg/utils/transmission-show.exe" "-D" "torrent_file:string=assets/ubuntu-20.04.3-desktop-amd64.iso.torrent" "-D" "reference_file:string=X:/transmission-jr/tests/utils/assets/ubuntu-20.04.3-desktop-amd64.iso.show" "-P" "X:/transmission-jr/tests/utils/run_transmission_show.cmake")
set_tests_properties(transmission-show-ubuntu PROPERTIES  WORKING_DIRECTORY "X:/transmission-jr/tests/utils" _BACKTRACE_TRIPLES "X:/transmission-jr/tests/utils/CMakeLists.txt;2;add_test;X:/transmission-jr/tests/utils/CMakeLists.txt;17;AddShowTest;X:/transmission-jr/tests/utils/CMakeLists.txt;0;")
add_test(transmission-show-ubuntu-hybrid "X:/cmake/bin/cmake.exe" "-D" "transmission_show:string=X:/transmission-jr/build-dbg/utils/transmission-show.exe" "-D" "torrent_file:string=assets/hybrid-single-ubuntu-20.04.3-desktop-amd64.iso.torrent" "-D" "reference_file:string=X:/transmission-jr/tests/utils/assets/hybrid-single-ubuntu-20.04.3-desktop-amd64.iso.show" "-P" "X:/transmission-jr/tests/utils/run_transmission_show.cmake")
set_tests_properties(transmission-show-ubuntu-hybrid PROPERTIES  WORKING_DIRECTORY "X:/transmission-jr/tests/utils" _BACKTRACE_TRIPLES "X:/transmission-jr/tests/utils/CMakeLists.txt;2;add_test;X:/transmission-jr/tests/utils/CMakeLists.txt;18;AddShowTest;X:/transmission-jr/tests/utils/CMakeLists.txt;0;")
add_test(transmission-show-bitcomet-path.utf8 "X:/cmake/bin/cmake.exe" "-D" "transmission_show:string=X:/transmission-jr/build-dbg/utils/transmission-show.exe" "-D" "torrent_file:string=assets/bitcomet.utf-8.special.torrent" "-D" "reference_file:string=X:/transmission-jr/tests/utils/assets/bitcomet.utf-8.special.show" "-P" "X:/transmission-jr/tests/utils/run_transmission_show.cmake")
set_tests_properties(transmission-show-bitcomet-path.utf8 PROPERTIES  WORKING_DIRECTORY "X:/transmission-jr/tests/utils" _BACKTRACE_TRIPLES "X:/transmission-jr/tests/utils/CMakeLists.txt;2;add_test;X:/transmission-jr/tests/utils/CMakeLists.txt;19;AddShowTest;X:/transmission-jr/tests/utils/CMakeLists.txt;0;")
