.Dd June 26, 2010
.Dt TRANSMISSION-QT 1
.Sh NAME
.Nm transmission-qt
.Nd a bittorrent client
.Sh SYNOPSIS
.Nm transmission-qt
.Fl h
.Nm
.Op Nm options
.Op Ar torrent-file ...
.Sh DESCRIPTION
.Nm
is a fast and easy BitTorrent client.
.Pp
BitTorrent is a peer-to-peer file transfer protocol which uses a
metainfo file (usually with the .torrent file extension) and a central
tracker to distribute file data amongst a group of peers. For more
information on the BitTorrent protocol see http://www.bittorrent.org/
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl h Fl -help
Show help options
.It Fl g Fl -config-dir Ar directory
Where to look for configuration files. This can be used to swap between using the cli, daemon, gtk, and qt clients.
See https://github.com/transmission/transmission/blob/main/docs/Configuration-Files.md for more information.
.It Fl m Fl -minimized
Start minimized in notification area
.It Fl p Fl -port Ar port
Port to use when connecting to an existing session
.It Fl r Fl -remote Ar host
Connect to an existing session at the specified hostname
.It Fl u Fl -username Ar username
Username to use when connecting to an existing session
.It Fl v Fl -version
Show version number and exit
.It Fl w Fl -password Ar password
Password to use when connecting to an existing session
.El
.Pp
Multiple .torrent files may be added at startup
by appending them on the command line. If
.Nm
is already running, the torrents will be added to the running instance.
.Sh ENVIRONMENT
.Bl -tag -width Fl
.It Ev TRANSMISSION_HOME
Sets the default config-dir.
.El
.Sh FILES
.Bl -tag -width Ds -compact
.It ~/.config/transmission
The config-dir used when neither
.Op Ev TRANSMISSION_HOME
nor
.Op Fl g
is specified.
.El
.Sh AUTHORS
.An -nosplit
.Nm
was written by
.An Charles Kerr ,
.An Josh Elsasser ,
.An Eric Petit ,
.An Mitchell Livingston ,
and
.An Mike Gelfand .
.Sh SEE ALSO
.Xr transmission-create 1 ,
.Xr transmission-daemon 1 ,
.Xr transmission-edit 1 ,
.Xr transmission-gtk 1 ,
.Xr transmission-qt 1 ,
.Xr transmission-remote 1 ,
.Xr transmission-show 1
.Pp
https://transmissionbt.com/
