import "ocidl.idl";

[
	uuid(1E405FC2-1A3A-468B-8BD6-BFBB58770390),
	version(1.0),
	helpstring("Transmission Qt Client Type Library 1.0")
]
library TransmissionLib
{
	[
		uuid(9402F54F-4906-4F20-AD73-AFCFEB5B228D),
		helpstring("QtClient Interface")
	]
	dispinterface IQtClient
	{
	properties:

	methods:
		[id(1)] VARIANT_BOOL PresentWindow();
		[id(2)] VARIANT_BOOL AddMetainfo([in] BSTR p_metainfo);
	};

	[
		aggregatable,
		appobject,
		helpstring("Transmission Qt Client Class"),
		uuid(0E2C952C-0597-491F-BA26-249D7E6FAB49)
	]
	coclass QtClient
	{
		[default] dispinterface IQtClient;
	};
};
