EXECUTE_PROCESS(
    COMMAND yarn install
    WORKING_DIRECTORY "${CPACK_TEMPORARY_INSTALL_DIRECTORY}/web"
)
EXECUTE_PROCESS(
    COMMAND yarn build
    WORKING_DIRECTORY "${CPACK_TEMPORARY_INSTALL_DIRECTORY}/web"
)
FILE(
    REMOVE_RECURSE
    "${CPACK_TEMPORARY_INSTALL_DIRECTORY}/web/node_modules"
)
